export const LAWS = [
  { number: 1, name: 'מגרש המשחק' },
  { number: 2, name: 'הכדור' },
  { number: 3, name: 'השחקנים' },
  { number: 4, name: 'ציוד השחקנים' },
  { number: 5, name: 'השופט' },
  { number: 6, name: 'שאר שופטי המשחק' },
  { number: 7, name: 'משך המשחק' },
  { number: 8, name: 'התחלת וחידוש המשחק' },
  { number: 9, name: 'הכדור במשחק ומחוץ למשחק' },
  { number: 10, name: 'קביעת תוצאת המשחק' },
  { number: 11, name: 'נבדל' },
  { number: 12, name: 'עבירות והתנהגות בלתי ספורטיבית' },
  { number: 13, name: 'בעיטות חופשיות' },
  { number: 14, name: 'בעיטת עונשין' },
  { number: 15, name: 'הוצאת חוץ' },
  { number: 16, name: 'בעיטת שער' },
  { number: 17, name: 'בעיטת קרן' },
];
